### ISSUE TITLE
Setup basic application layout

### ISSUE THREAD

**Issue by diegotoral** [diegotoral/pressy#13]
## ToDo

- [x] Update `app/views/layouts/application.html.erb` to use webpacker tags
- [x] Display flash messages
- [x] Set lang on html tag
- [x] Display navigation bar
